const express = require("express")
const cors = require("cors")
const authRouter = require("./routes/v1/authRouter")
const userRouter = require("./routes/v1/userRouter")
const categoryRouter = require("./routes/v1/categoryRouter")
const courseRouter = require("./routes/v1/courseRouter")
const commentRouter = require("./routes/v1/commentRouter")
const contactRouter = require("./routes/v1/contactRouter")
const newsletterRouter = require("./routes/v1/newsletterRouter")
const searchRouter = require("./routes/v1/searchRouter")
const notificationRouter = require("./routes/v1/notificationRouter")
const offRouter = require("./routes/v1/offRouter")
const articleRouter = require("./routes/v1/articleRouter")
const orderRouter = require("./routes/v1/orderRouter")
const ticketRouter = require("./routes/v1/ticketRouter")

const app = express()

app.use(cors())
app.use(express.json())
app.use(express.urlencoded({ extended: false }))

app.use("/api/v1/auth", authRouter)
app.use("/api/v1/user", userRouter)
app.use("/api/v1/category", categoryRouter)
app.use("/api/v1/courses", courseRouter)
app.use("/api/v1/comments", commentRouter)
app.use("/api/v1/contact", contactRouter)
app.use("/api/v1/newsletters", newsletterRouter)
app.use("/api/v1/search", searchRouter)
app.use("/api/v1/notifications", notificationRouter)
app.use("/api/v1/offs", offRouter)
app.use("/api/v1/articles", articleRouter)
app.use("/api/v1/order", orderRouter)
app.use("/api/v1/tickets", ticketRouter)

module.exports = app